version: "3.2"

services:
  dev:
    container_name: node-template
    image: paritytech/ci-linux:production
    working_dir: /var/www/node-template
    ports:
      - "9944:10086"
    environment:
      - CARGO_HOME=/var/www/node-template/.cargo
    volumes:
      - .:/var/www/node-template
      - type: bind
        source: ./
        target: /root/
    command: bash -c "cargo build --release && ./target/release/node-template --dev --ws-external"
